version: "3"

services:
  app:
    build: .
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    links:
      - mongo
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    image: mvertes/alpine-mongo